---
  - name: Python | Install
    apt: pkg={{item}} state=present
    with_items:
      - python
      - python-dev
      - python-pip
    when: ansible_os_family == "Debian"
    become: yes

  - name: Python | Install latest pip
    shell: curl https://bootstrap.pypa.io/get-pip.py | python
    when: ansible_os_family == "Debian"
    become: yes

  - name: Python | Upgrade setuptools
    command: pip install --upgrade setuptools
    when: ansible_os_family == "Debian"
    become: yes
